name: QCardEst
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h993c535_1
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
    - certifi==2025.4.26
    - cffi==1.17.1
    - charset-normalizer==3.4.2
    - cryptography==45.0.4
    - dill==0.3.5.1
    - fastdtw==0.3.4
    - filelock==3.18.0
    - fsspec==2025.5.1
    - idna==3.10
    - jinja2==3.1.6
    - joblib==1.5.1
    - markupsafe==3.0.2
    - mpmath==1.3.0
    - networkx==3.4.2
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.19.3
    - nvidia-nvjitlink-cu12==12.9.86
    - nvidia-nvtx-cu12==12.1.105
    - pbr==6.1.1
    - ply==3.11
    - psutil==7.0.0
    - pycparser==2.22
    - pyspnego==0.11.2
    - python-dateutil==2.9.0.post0
    - qiskit==0.39.2
    - qiskit-aer==0.11.1
    - qiskit-ibmq-provider==0.19.2
    - qiskit-machine-learning==0.5.0
    - qiskit-terra==0.22.2
    - requests==2.32.4
    - requests-ntlm==1.3.0
    - retworkx==0.16.0
    - rustworkx==0.16.0
    - scikit-learn==1.7.0
    - scipy==1.15.3
    - six==1.17.0
    - stevedore==5.4.1
    - symengine==0.14.1
    - sympy==1.14.0
    - threadpoolctl==3.6.0
    - torch==2.2.2
    - triton==2.2.0
    - tweedledum==1.1.1
    - typing-extensions==4.14.0
    - urllib3==2.4.0
    - websocket-client==1.8.0
    - websockets==15.0.1
prefix: /home/winker/anaconda3/envs/QCardEst
